playerNames = [{'fpl': 1, 'name': 'Shkodran Mustafi', 'understat': 1699, 'position': 'DEF', 'starter': False},
               {'fpl': 2, 'name': 'Héctor Bellerín', 'understat': 492, 'position': 'DEF', 'starter': False},
               {'fpl': 3, 'name': 'Sead Kolasinac', 'understat': 342, 'position': 'DEF', 'starter': False},
               {'fpl': 4, 'name': 'Ainsley Maitland-Niles', 'understat': 1750, 'position': 'DEF', 'starter': False},
               {'fpl': 5, 'name': 'Sokratis Papastathopoulos', 'understat': 371, 'position': 'DEF', 'starter': True},
               {'fpl': 6, 'name': 'Nacho Monreal', 'understat': 495, 'position': 'DEF', 'starter': False},
               {'fpl': 7, 'name': 'Laurent Koscielny', 'understat': 494, 'position': 'DEF', 'starter': False},
               {'fpl': 8, 'name': 'Konstantinos Mavropanos', 'understat': 6722, 'position': 'DEF', 'starter': False},
               {'fpl': 9, 'name': 'Carl Jenkinson', 'understat': 938, 'position': 'DEF', 'starter': False},
               {'fpl': 10, 'name': 'Rob Holding', 'understat': 1749, 'position': 'DEF', 'starter': False},
               {'fpl': 11, 'name': 'Pierre-Emerick Aubameyang', 'understat': 318, 'position': 'FOR', 'starter': True},
               {'fpl': 12, 'name': 'Alexandre Lacazette', 'understat': 3277, 'position': 'FOR', 'starter': True},
               {'fpl': 13, 'name': 'Edward Nketiah', 'understat': 6482, 'position': 'FOR', 'starter': False},
               {'fpl': 14, 'name': 'Bernd Leno', 'understat': 181, 'position': 'GKP', 'starter': True},
               {'fpl': 15, 'name': 'Mesut Özil', 'understat': 499, 'position': 'MID', 'starter': True},
               {'fpl': 16, 'name': 'Henrikh Mkhitaryan', 'understat': 317, 'position': 'MID', 'starter': False},
               {'fpl': 18, 'name': 'Granit Xhaka', 'understat': 204, 'position': 'MID', 'starter': True},
               {'fpl': 19, 'name': 'Lucas Torreira', 'understat': 1227, 'position': 'MID', 'starter': True},
               {'fpl': 20, 'name': 'Mohamed Elneny', 'understat': 496, 'position': 'MID', 'starter': False},
               {'fpl': 21, 'name': 'Matteo Guendouzi', 'understat': 5759, 'position': 'MID', 'starter': True},
               {'fpl': 106, 'name': 'David Luiz', 'understat': 1676, 'position': 'DEF', 'starter': True},
               {'fpl': 427, 'name': 'Emiliano Martínez', 'understat': 4401, 'position': 'GKP', 'starter': False},
               {'fpl': 467, 'name': 'Calum Chambers', 'understat': 508, 'position': 'DEF', 'starter': True},
               {'fpl': 469, 'name': 'Dani Ceballos', 'understat': 2446, 'position': 'MID', 'starter': True},
               {'fpl': 488, 'name': 'Nicolas Pépé', 'understat': 5656, 'position': 'MID', 'starter': True},
               {'fpl': 489, 'name': 'Reiss Nelson', 'understat': 6492, 'position': 'MID', 'starter': False},
               {'fpl': 490, 'name': 'Joseph Willock', 'understat': 6630, 'position': 'MID', 'starter': False},
               {'fpl': 504, 'name': 'Gabriel Teodoro Martinelli Silva', 'understat': 7752, 'position': 'FOR', 'starter': False},
               {'fpl': 515, 'name': 'Kieran Tierney', 'understat': 8089, 'position': 'DEF', 'starter': True},
               {'fpl': 541, 'name': 'Bukayo Saka', 'understat': 7322, 'position': 'MID', 'starter': True},
               {'fpl': 576, 'name': 'Emile Smith Rowe', 'understat': 7230, 'position': 'MID', 'starter': False},
               {'fpl': 22, 'name': 'Ahmed El Mohamady', 'understat': 1685, 'position': 'DEF', 'starter': False},
               {'fpl': 23, 'name': 'James Chester', 'understat': 819, 'position': 'DEF', 'starter': False},
               {'fpl': 24, 'name': 'Neil Taylor', 'understat': 710, 'position': 'DEF', 'starter': False},
               {'fpl': 25, 'name': 'Kortney Hause', 'understat': 6859, 'position': 'DEF', 'starter': False},
               {'fpl': 26, 'name': 'Jonathan Kodjia', 'understat': 7725, 'position': 'FOR', 'starter': False},
               {'fpl': 27, 'name': 'Ørjan Nyland', 'understat': 250, 'position': 'GKP', 'starter': False},
               {'fpl': 28, 'name': 'Conor Hourihane', 'understat': 7721, 'position': 'MID', 'starter': True},
               {'fpl': 29, 'name': 'Jack Grealish', 'understat': 675, 'position': 'MID', 'starter': True},
               {'fpl': 30, 'name': 'Anwar El Ghazi', 'understat': 5612, 'position': 'MID', 'starter': True},
               {'fpl': 31, 'name': 'John McGinn', 'understat': 7723, 'position': 'MID', 'starter': True},
               {'fpl': 32, 'name': 'Andre Green', 'understat': 874, 'position': 'MID', 'starter': False},
               {'fpl': 33, 'name': 'Birkir Bjarnason', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 34, 'name': 'Keinan Davis', 'understat': 1053, 'position': 'MID', 'starter': False},
               {'fpl': 35, 'name': 'Henri Lansbury', 'understat': 7727, 'position': 'MID', 'starter': False},
               {'fpl': 36, 'name': 'Trézéguet', 'understat': 2132, 'position': 'MID', 'starter': True},
               {'fpl': 94, 'name': 'Tom Heaton', 'understat': 1651, 'position': 'GKP', 'starter': True},
               {'fpl': 309, 'name': 'Matt Targett', 'understat': 884, 'position': 'DEF', 'starter': True},
               {'fpl': 428, 'name': 'Wesley Moraes', 'understat': 7724, 'position': 'FOR', 'starter': True},
               {'fpl': 429, 'name': 'Jed Steer', 'understat': 4475, 'position': 'GKP', 'starter': False},
               {'fpl': 445, 'name': 'Tyrone Mings', 'understat': 1024, 'position': 'DEF', 'starter': False},
               {'fpl': 452, 'name': 'Ezri Konsa Ngoyo', 'understat': 7726, 'position': 'DEF', 'starter': False},
               {'fpl': 455, 'name': 'Bjorn Engels', 'understat': 7152, 'position': 'DEF', 'starter': True},
               {'fpl': 458, 'name': 'Frédéric Guilbert', 'understat': 3253, 'position': 'DEF', 'starter': True},
               {'fpl': 465, 'name': 'Mahmoud Ahmed Ibrahim Hassan', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 470, 'name': 'Douglas Luiz', 'understat': 6122, 'position': 'MID', 'starter': True},
               {'fpl': 474, 'name': 'Lovre Kalinic', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 491, 'name': 'Marvelous Nakamba', 'understat': 8040, 'position': 'MID', 'starter': True},
               {'fpl': 58, 'name': 'Steve Cook', 'understat': 458, 'position': 'DEF', 'starter': False},
               {'fpl': 59, 'name': 'Nathan Akê', 'understat': 579, 'position': 'DEF', 'starter': False},
               {'fpl': 60, 'name': 'Charlie Daniels', 'understat': 459, 'position': 'DEF', 'starter': False},
               {'fpl': 61, 'name': 'Chris Mepham', 'understat': 7384, 'position': 'DEF', 'starter': True},
               {'fpl': 62, 'name': 'Simon Francis', 'understat': 456, 'position': 'DEF', 'starter': True},
               {'fpl': 63, 'name': 'Adam Smith', 'understat': 825, 'position': 'MID', 'starter': False},
               {'fpl': 64, 'name': 'Lloyd Kelly', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 65, 'name': 'Diego Rico', 'understat': 5065, 'position': 'DEF', 'starter': True},
               {'fpl': 66, 'name': 'Jack Simpson', 'understat': 6410, 'position': 'DEF', 'starter': False},
               {'fpl': 67, 'name': 'Callum Wilson', 'understat': 468, 'position': 'FOR', 'starter': True},
               {'fpl': 68, 'name': 'Joshua King', 'understat': 465, 'position': 'FOR', 'starter': True},
               {'fpl': 69, 'name': 'Dominic Solanke', 'understat': 1679, 'position': 'FOR', 'starter': False},
               {'fpl': 71, 'name': 'Sam Surridge', 'understat': 5602, 'position': 'FOR', 'starter': False},
               {'fpl': 72, 'name': 'Asmir Begovic', 'understat': 694, 'position': 'GKP', 'starter': False},
               {'fpl': 73, 'name': 'Artur Boruc', 'understat': 455, 'position': 'GKP', 'starter': False},
               {'fpl': 74, 'name': 'Mark Travers', 'understat': 7582, 'position': 'GKP', 'starter': False},
               {'fpl': 75, 'name': 'Ryan Fraser', 'understat': 1683, 'position': 'MID', 'starter': True},
               {'fpl': 76, 'name': 'David Brooks', 'understat': 6820, 'position': 'MID', 'starter': False},
               {'fpl': 77, 'name': 'Junior Stanislas', 'understat': 463, 'position': 'MID', 'starter': False},
               {'fpl': 78, 'name': 'Jordon Ibe', 'understat': 481, 'position': 'MID', 'starter': False},
               {'fpl': 79, 'name': 'Lewis Cook', 'understat': 1789, 'position': 'MID', 'starter': False},
               {'fpl': 80, 'name': 'Andrew Surman', 'understat': 460, 'position': 'MID', 'starter': False},
               {'fpl': 81, 'name': 'Dan Gosling', 'understat': 462, 'position': 'MID', 'starter': False},
               {'fpl': 82, 'name': 'Jefferson Lerma', 'understat': 2182, 'position': 'MID', 'starter': False},
               {'fpl': 446, 'name': 'Jack Stacey', 'understat': 7823, 'position': 'DEF', 'starter': True},
               {'fpl': 476, 'name': 'Philip Billing', 'understat': 6034, 'position': 'MID', 'starter': True},
               {'fpl': 492, 'name': 'Arnaut Danjuma Groeneveld', 'understat': 8066, 'position': 'MID', 'starter': False},
               {'fpl': 494, 'name': 'Aaron Ramsdale', 'understat': 5603, 'position': 'GKP', 'starter': True},
               {'fpl': 505, 'name': 'Harry Wilson', 'understat': 5596, 'position': 'MID', 'starter': True},
               {'fpl': 564, 'name': 'Christian Saydee', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 565, 'name': 'Gavin Kilkenny', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 574, 'name': 'Mihai-Alexandru Dobre', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 37, 'name': 'Shane Duffy', 'understat': 6047, 'position': 'DEF', 'starter': False},
               {'fpl': 38, 'name': 'Martín Montoya', 'understat': 1950, 'position': 'DEF', 'starter': True},
               {'fpl': 39, 'name': 'Bernardo Fernandes da Silva Junior', 'understat': 5245, 'position': 'DEF', 'starter': False},
               {'fpl': 40, 'name': 'Leon Balogun', 'understat': 394, 'position': 'DEF', 'starter': False},
               {'fpl': 41, 'name': 'Gaëtan Bong', 'understat': 6105, 'position': 'DEF', 'starter': False},
               {'fpl': 42, 'name': 'Lewis Dunk', 'understat': 6048, 'position': 'DEF', 'starter': True},
               {'fpl': 43, 'name': 'Matthew Clarke', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 44, 'name': 'Glenn Murray', 'understat': 882, 'position': 'FOR', 'starter': False},
               {'fpl': 45, 'name': 'Jürgen Locadia', 'understat': 6542, 'position': 'FOR', 'starter': False},
               {'fpl': 46, 'name': 'Florin Andone', 'understat': 4068, 'position': 'FOR', 'starter': False},
               {'fpl': 47, 'name': 'Mathew Ryan', 'understat': 2385, 'position': 'GKP', 'starter': True},
               {'fpl': 48, 'name': 'David Button', 'understat': 6843, 'position': 'GKP', 'starter': False},
               {'fpl': 49, 'name': 'Pascal Groß', 'understat': 239, 'position': 'MID', 'starter': True},
               {'fpl': 50, 'name': 'Alireza Jahanbakhsh', 'understat': 6842, 'position': 'MID', 'starter': False},
               {'fpl': 51, 'name': 'José Heriberto Izquierdo Mena', 'understat': 6231, 'position': 'MID', 'starter': False},
               {'fpl': 52, 'name': 'Anthony Knockaert', 'understat': 4497, 'position': 'MID', 'starter': False},
               {'fpl': 53, 'name': 'Yves Bissouma', 'understat': 5609, 'position': 'MID', 'starter': False},
               {'fpl': 54, 'name': 'Davy Pröpper', 'understat': 6050, 'position': 'MID', 'starter': True},
               {'fpl': 55, 'name': 'Solomon March', 'understat': 6049, 'position': 'MID', 'starter': False},
               {'fpl': 56, 'name': 'Beram Kayal', 'understat': 6409, 'position': 'MID', 'starter': False},
               {'fpl': 57, 'name': 'Dale Stephens', 'understat': 6051, 'position': 'MID', 'starter': False},
               {'fpl': 421, 'name': 'Leandro Trossard', 'understat': 7698, 'position': 'MID', 'starter': True},
               {'fpl': 475, 'name': 'Dan Burn', 'understat': 7382, 'position': 'DEF', 'starter': True},
               {'fpl': 493, 'name': 'Adam Webster', 'understat': 7699, 'position': 'DEF', 'starter': True},
               {'fpl': 502, 'name': 'Neal Maupay', 'understat': 3621, 'position': 'FOR', 'starter': True},
               {'fpl': 516, 'name': 'Aaron Mooy', 'understat': 6033, 'position': 'MID', 'starter': True},
               {'fpl': 534, 'name': 'Aaron Connolly', 'understat': 7991, 'position': 'FOR', 'starter': True},
               {'fpl': 536, 'name': 'Tudor Baluta', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 537, 'name': 'Steven Alzate', 'understat': 8020, 'position': 'MID', 'starter': False},
               {'fpl': 546, 'name': 'Ezequiel Schelotto', 'understat': 3873, 'position': 'DEF', 'starter': False},
               {'fpl': 83, 'name': 'Ben Mee', 'understat': 1654, 'position': 'DEF', 'starter': True},
               {'fpl': 84, 'name': 'James Tarkowski', 'understat': 1665, 'position': 'DEF', 'starter': True},
               {'fpl': 85, 'name': 'Matthew Lowton', 'understat': 1652, 'position': 'DEF', 'starter': True},
               {'fpl': 86, 'name': 'Phil Bardsley', 'understat': 857, 'position': 'DEF', 'starter': False},
               {'fpl': 87, 'name': 'Charlie Taylor', 'understat': 6044, 'position': 'DEF', 'starter': True},
               {'fpl': 88, 'name': 'Kevin Long', 'understat': 1747, 'position': 'DEF', 'starter': False},
               {'fpl': 89, 'name': 'Ben Gibson', 'understat': 1707, 'position': 'DEF', 'starter': False},
               {'fpl': 90, 'name': 'Ashley Barnes', 'understat': 4422, 'position': 'FOR', 'starter': True},
               {'fpl': 91, 'name': 'Chris Wood', 'understat': 4456, 'position': 'FOR', 'starter': True},
               {'fpl': 92, 'name': 'Matej Vydra', 'understat': 1017, 'position': 'FOR', 'starter': False},
               {'fpl': 93, 'name': 'Nick Pope', 'understat': 5552, 'position': 'GKP', 'starter': True},
               {'fpl': 95, 'name': 'Joe Hart', 'understat': 609, 'position': 'GKP', 'starter': False},
               {'fpl': 96, 'name': 'Johann Berg Gudmundsson', 'understat': 1663, 'position': 'MID', 'starter': False},
               {'fpl': 97, 'name': 'Dwight McNeil', 'understat': 6756, 'position': 'MID', 'starter': True},
               {'fpl': 98, 'name': 'Robbie Brady', 'understat': 789, 'position': 'MID', 'starter': False},
               {'fpl': 99, 'name': 'Steven Defour', 'understat': 1657, 'position': 'MID', 'starter': False},
               {'fpl': 100, 'name': 'Jeff Hendrick', 'understat': 1746, 'position': 'MID', 'starter': False},
               {'fpl': 101, 'name': 'Ashley Westwood', 'understat': 669, 'position': 'MID', 'starter': True},
               {'fpl': 102, 'name': 'Jack Cork', 'understat': 712, 'position': 'MID', 'starter': True},
               {'fpl': 120, 'name': 'Daniel Drinkwater', 'understat': 752, 'position': 'MID', 'starter': False},
               {'fpl': 430, 'name': 'Aaron Lennon', 'understat': 593, 'position': 'MID', 'starter': False},
               {'fpl': 447, 'name': 'Erik Pieters', 'understat': 887, 'position': 'DEF', 'starter': True},
               {'fpl': 451, 'name': 'Jay Rodriguez', 'understat': 844, 'position': 'FOR', 'starter': True},
               {'fpl': 495, 'name': 'Bailey Peacock-Farrell', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 571, 'name': 'Mace Goodridge', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 572, 'name': 'Anthony Driscoll-Glennon', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 103, 'name': 'Marcos Alonso', 'understat': 1621, 'position': 'DEF', 'starter': True},
               {'fpl': 104, 'name': 'Antonio Rüdiger', 'understat': 1822, 'position': 'DEF', 'starter': True},
               {'fpl': 105, 'name': 'César Azpilicueta', 'understat': 681, 'position': 'DEF', 'starter': True},
               {'fpl': 107, 'name': 'Emerson Palmieri dos Santos', 'understat': 1245, 'position': 'DEF', 'starter': False},
               {'fpl': 108, 'name': 'Andreas Christensen', 'understat': 200, 'position': 'DEF', 'starter': True},
               {'fpl': 109, 'name': 'Davide Zappacosta', 'understat': 1178, 'position': 'DEF', 'starter': False},
               {'fpl': 110, 'name': 'Olivier Giroud', 'understat': 502, 'position': 'FOR', 'starter': False},
               {'fpl': 111, 'name': 'Kepa Arrizabalaga', 'understat': 5061, 'position': 'GKP', 'starter': True},
               {'fpl': 112, 'name': 'Willy Caballero', 'understat': 624, 'position': 'GKP', 'starter': False},
               {'fpl': 113, 'name': 'Willian', 'understat': 700, 'position': 'MID', 'starter': True},
               {'fpl': 114, 'name': 'Pedro Rodríguez Ledesma', 'understat': 687, 'position': 'MID', 'starter': False},
               {'fpl': 115, 'name': 'Ruben Loftus-Cheek', 'understat': 688, 'position': 'MID', 'starter': False},
               {'fpl': 116, 'name': 'Callum Hudson-Odoi', 'understat': 6456, 'position': 'MID', 'starter': False},
               {'fpl': 117, 'name': 'Ross Barkley', 'understat': 592, 'position': 'MID', 'starter': False},
               {'fpl': 118, 'name': 'Jorginho', 'understat': 1389, 'position': 'MID', 'starter': True},
               {'fpl': 119, 'name': "N'Golo Kanté", 'understat': 751, 'position': 'MID', 'starter': True},
               {'fpl': 121, 'name': 'Ethan Ampadu', 'understat': 6369, 'position': 'MID', 'starter': False},
               {'fpl': 431, 'name': 'Christian Pulisic', 'understat': 2662, 'position': 'MID', 'starter': True},
               {'fpl': 432, 'name': 'Mateo Kovacic', 'understat': 2254, 'position': 'MID', 'starter': True},
               {'fpl': 459, 'name': 'Kurt Zouma', 'understat': 935, 'position': 'DEF', 'starter': True},
               {'fpl': 460, 'name': 'Tammy Abraham', 'understat': 702, 'position': 'FOR', 'starter': True},
               {'fpl': 461, 'name': 'Michy Batshuayi', 'understat': 1678, 'position': 'FOR', 'starter': False},
               {'fpl': 462, 'name': 'Robert Kenedy Nunes do Nascimento', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 463, 'name': 'Mason Mount', 'understat': 7768, 'position': 'MID', 'starter': True},
               {'fpl': 506, 'name': 'Reece James', 'understat': 8067, 'position': 'DEF', 'starter': False},
               {'fpl': 529, 'name': 'Fikayo Tomori', 'understat': 703, 'position': 'DEF', 'starter': True},
               {'fpl': 533, 'name': 'Billy Gilmour', 'understat': 7988, 'position': 'MID', 'starter': False},
               {'fpl': 545, 'name': 'Addji Keaninkin Marc-Israel Guehi', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 123, 'name': 'Patrick van Aanholt', 'understat': 730, 'position': 'DEF', 'starter': False},
               {'fpl': 124, 'name': 'James Tomkins', 'understat': 530, 'position': 'DEF', 'starter': True},
               {'fpl': 125, 'name': 'Mamadou Sakho', 'understat': 485, 'position': 'DEF', 'starter': True},
               {'fpl': 126, 'name': 'Joel Ward', 'understat': 510, 'position':'DEF', 'starter': False},
               {'fpl': 127, 'name': 'Scott Dann', 'understat': 512, 'position': 'DEF', 'starter': True},
               {'fpl': 128, 'name': 'Martin Kelly', 'understat': 525, 'position': 'DEF', 'starter': True},
               {'fpl': 129, 'name': 'Christian Benteke', 'understat': 606, 'position': 'FOR', 'starter': True},
               {'fpl': 130, 'name': 'Connor Wickham', 'understat': 519, 'position': 'FOR', 'starter': False},
               {'fpl': 131, 'name': 'Vicente Guaita', 'understat': 2190, 'position': 'GKP', 'starter': True},
               {'fpl': 132, 'name': 'Wayne Hennessey', 'understat': 509, 'position': 'GKP', 'starter': False},
               {'fpl': 133, 'name': 'Wilfried Zaha', 'understat': 522, 'position': 'MID', 'starter': True},
               {'fpl': 134, 'name': 'Luka Milivojevic', 'understat': 5549, 'position': 'MID', 'starter': True},
               {'fpl': 135, 'name': 'Andros Townsend', 'understat': 775, 'position': 'MID', 'starter': True},
               {'fpl': 136, 'name': 'Max Meyer', 'understat': 338, 'position': 'MID', 'starter': False},
               {'fpl': 137, 'name': 'Jeffrey Schlupp', 'understat': 757, 'position': 'MID', 'starter': False},
               {'fpl': 138, 'name': 'James McArthur', 'understat': 633, 'position': 'MID', 'starter': False},
               {'fpl': 139, 'name': 'Cheikhou Kouyaté', 'understat': 532, 'position': 'MID', 'starter': True},
               {'fpl': 140, 'name': 'Luke Dreher', 'understat': 636, 'position': 'MID', 'starter': False},
               {'fpl': 157, 'name': 'James McCarthy', 'understat': 589, 'position': 'MID', 'starter': False},
               {'fpl': 468, 'name': 'Jordan Ayew', 'understat': 672, 'position': 'FOR', 'starter': True},
               {'fpl': 503, 'name': 'Gary Cahill', 'understat': 699, 'position': 'DEF', 'starter': False},
               {'fpl': 510, 'name': 'Víctor Camarasa', 'understat': 2390, 'position': 'MID', 'starter': False},
               {'fpl': 539, 'name': 'Jairo Riedewald', 'understat': 6027, 'position': 'MID', 'starter': False},
               {'fpl': 556, 'name': 'Stephen Henderson', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 17, 'name': 'Alex Iwobi', 'understat': 500, 'position': 'MID', 'starter': False},
               {'fpl': 141, 'name': 'Lucas Digne', 'understat': 1823, 'position': 'DEF', 'starter': True},
               {'fpl': 142, 'name': 'Yerry Mina', 'understat': 6521, 'position': 'DEF', 'starter': True},
               {'fpl': 143, 'name': 'Michael Keane', 'understat': 1653, 'position': 'DEF', 'starter': True},
               {'fpl': 144, 'name': 'Seamus Coleman', 'understat': 585, 'position': 'DEF', 'starter': False},
               {'fpl': 145, 'name': 'Leighton Baines', 'understat': 588, 'position': 'DEF', 'starter': False},
               {'fpl': 146, 'name': 'Cenk Tosun', 'understat': 6477, 'position': 'FOR', 'starter': False},
               {'fpl': 147, 'name': 'Dominic Calvert-Lewin', 'understat': 5555, 'position': 'FOR', 'starter': True},
               {'fpl': 148, 'name': 'Jordan Pickford', 'understat': 741, 'position': 'GKP', 'starter': True},
               {'fpl': 149, 'name': 'Maarten Stekelenburg', 'understat': 846, 'position': 'GKP', 'starter': False},
               {'fpl': 150, 'name': 'Richarlison de Andrade', 'understat': 6026, 'position': 'MID', 'starter': True},
               {'fpl': 151, 'name': 'Gylfi Sigurdsson', 'understat': 714, 'position': 'MID', 'starter': True},
               {'fpl': 152, 'name': 'Bernard Anício Caldeira Duarte', 'understat': 7063, 'position': 'MID', 'starter': False},
               {'fpl': 153, 'name': 'Theo Walcott', 'understat': 503, 'position': 'MID', 'starter': True},
               {'fpl': 154, 'name': 'Tom Davies', 'understat': 1042, 'position': 'MID', 'starter': True},
               {'fpl': 155, 'name': 'Ademola Lookman', 'understat': 5556, 'position': 'MID', 'starter': False},
               {'fpl': 156, 'name': 'Idrissa Gueye', 'understat': 668, 'position': 'MID', 'starter': False},
               {'fpl': 158, 'name': 'Morgan Schneiderlin', 'understat': 551, 'position': 'MID', 'starter': False},
               {'fpl': 205, 'name': 'Fabian Delph', 'understat': 876, 'position': 'MID', 'starter': False},
               {'fpl': 422, 'name': 'André Filipe Tavares Gomes', 'understat': 2383, 'position': 'MID', 'starter': False},
               {'fpl': 477, 'name': 'Lewis Gibson', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 478, 'name': 'Mason Holgate', 'understat': 985, 'position': 'DEF', 'starter': True},
               {'fpl': 479, 'name': 'Jonas Lössl', 'understat': 3468, 'position': 'GKP', 'starter': False},
               {'fpl': 496, 'name': 'Moise Kean', 'understat': 1304, 'position': 'FOR', 'starter': False},
               {'fpl': 497, 'name': 'Jean-Philippe Gbamin', 'understat': 4764, 'position': 'MID', 'starter': False},
               {'fpl': 511, 'name': 'Djibril Sidibé', 'understat': 3357, 'position': 'DEF', 'starter': False},
               {'fpl': 557, 'name': 'Beni Baningime', 'understat': 6384, 'position': 'MID', 'starter': False},
               {'fpl': 561, 'name': 'Anthony Gordon', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 570, 'name': 'Oumar Niasse', 'understat': 599, 'position': 'FOR', 'starter': False},
               {'fpl': 577, 'name': 'Rhu-endly Martina', 'understat': 832, 'position': 'DEF', 'starter': False},
               {'fpl': 159, 'name': 'Ricardo Pereira', 'understat': 3303, 'position': 'DEF', 'starter': True},
               {'fpl': 161, 'name': 'Benjamin Chilwell', 'understat': 782, 'position': 'DEF', 'starter': True},
               {'fpl': 162, 'name': 'Jonny Evans', 'understat': 807, 'position': 'DEF', 'starter': True},
               {'fpl': 163, 'name': 'Christian Fuchs', 'understat': 749, 'position': 'DEF', 'starter': False},
               {'fpl': 164, 'name': 'Çaglar Söyüncü', 'understat': 5264, 'position': 'DEF', 'starter': True},
               {'fpl': 165, 'name': 'Wes Morgan', 'understat': 748, 'position': 'DEF', 'starter': False},
               {'fpl': 166, 'name': 'Jamie Vardy', 'understat': 755, 'position': 'FOR', 'starter': True},
               {'fpl': 167, 'name': 'Kelechi Iheanacho', 'understat': 620, 'position': 'FOR', 'starter': False},
               {'fpl': 168, 'name': 'Kasper Schmeichel', 'understat': 745, 'position': 'GKP', 'starter': True},
               {'fpl': 169, 'name': 'Eldin Jakupovic', 'understat': 1697, 'position': 'GKP', 'starter': False},
               {'fpl': 170, 'name': 'Danny Ward', 'understat': 6830, 'position': 'GKP', 'starter': False},
               {'fpl': 171, 'name': 'James Maddison', 'understat': 6818, 'position': 'MID', 'starter': True},
               {'fpl': 172, 'name': 'Harvey Barnes', 'understat': 6681, 'position': 'MID', 'starter': True},
               {'fpl': 173, 'name': 'Rachid Ghezzal', 'understat': 3276, 'position': 'MID', 'starter': False},
               {'fpl': 174, 'name': 'Marc Albrighton', 'understat': 753, 'position': 'MID', 'starter': False},
               {'fpl': 175, 'name': 'Demarai Gray', 'understat': 762, 'position': 'MID', 'starter': False},
               {'fpl': 176, 'name': 'Wilfred Ndidi', 'understat': 5545, 'position': 'MID', 'starter': True},
               {'fpl': 177, 'name': 'Matty James', 'understat': 4441, 'position': 'MID', 'starter': False},
               {'fpl': 178, 'name': 'Daniel Amartey', 'understat': 759, 'position': 'MID', 'starter': False},
               {'fpl': 179, 'name': 'Nampalys Mendy', 'understat': 3389, 'position': 'MID', 'starter': False},
               {'fpl': 180, 'name': 'Hamza Choudhury', 'understat': 6418, 'position': 'MID', 'starter': False},
               {'fpl': 265, 'name': 'Ayoze Pérez', 'understat': 770, 'position': 'MID', 'starter': True},
               {'fpl': 433, 'name': 'James Justin', 'understat': 7753, 'position': 'DEF', 'starter': False},
               {'fpl': 448, 'name': 'Youri Tielemans', 'understat': 5956, 'position': 'MID', 'starter': True},
               {'fpl': 480, 'name': 'Andy King', 'understat': 784, 'position': 'MID', 'starter': False},
               {'fpl': 517, 'name': 'Dennis Praet', 'understat': 1234, 'position': 'MID', 'starter': False},
               {'fpl': 181, 'name': 'Andrew Robertson', 'understat': 1688, 'position': 'DEF', 'starter': True},
               {'fpl': 182, 'name': 'Trent Alexander-Arnold', 'understat': 1791, 'position': 'DEF', 'starter': True},
               {'fpl': 183, 'name': 'Virgil van Dijk', 'understat': 833, 'position': 'DEF', 'starter': True},
               {'fpl': 184, 'name': 'Joseph Gomez', 'understat': 987, 'position': 'DEF', 'starter': True},
               {'fpl': 185, 'name': 'Joel Matip', 'understat': 332, 'position': 'DEF', 'starter': False},
               {'fpl': 186, 'name': 'Dejan Lovren', 'understat': 602, 'position': 'DEF', 'starter': True},
               {'fpl': 187, 'name': 'Roberto Firmino', 'understat': 482, 'position': 'FOR', 'starter': True},
               {'fpl': 188, 'name': 'Divock Origi', 'understat': 484, 'position': 'FOR', 'starter': False},
               {'fpl': 189, 'name': 'Alisson Ramses Becker', 'understat': 1257, 'position': 'GKP', 'starter': True},
               {'fpl': 190, 'name': 'Simon Mignolet', 'understat': 487, 'position': 'GKP', 'starter': False},
               {'fpl': 191, 'name': 'Mohamed Salah', 'understat': 1250, 'position': 'MID', 'starter': True},
               {'fpl': 192, 'name': 'Sadio Mané', 'understat': 838, 'position': 'MID', 'starter': True},
               {'fpl': 193, 'name': 'Alex Oxlade-Chamberlain', 'understat': 966, 'position': 'MID', 'starter': True},
               {'fpl': 194, 'name': 'Xherdan Shaqiri', 'understat': 888, 'position': 'MID', 'starter': True},
               {'fpl': 195, 'name': 'Adam Lallana', 'understat': 486, 'position': 'MID', 'starter': False},
               {'fpl': 196, 'name': 'Naby Keita', 'understat': 5247, 'position': 'MID', 'starter': False},
               {'fpl': 197, 'name': 'Fabinho', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 198, 'name': 'Jordan Henderson', 'understat': 605, 'position': 'MID', 'starter': True},
               {'fpl': 199, 'name': 'Georginio Wijnaldum', 'understat': 771, 'position': 'MID', 'starter': True},
               {'fpl': 200, 'name': 'James Milner', 'understat': 489, 'position': 'MID', 'starter': True},
               {'fpl': 201, 'name': 'Rafael Camacho', 'understat': 6666, 'position': 'MID', 'starter': False},
               {'fpl': 464, 'name': 'Rhian Brewster', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 526, 'name': 'Adrián San Miguel del Castillo', 'understat': 527, 'position': 'GKP', 'starter': False},
               {'fpl': 530, 'name': 'Andy Lonergan', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 531, 'name': 'Caoimhin Kelleher', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 550, 'name': 'Harvey Elliott', 'understat': 7546, 'position': 'MID', 'starter': False},
               {'fpl': 569, 'name': 'Curtis Jones', 'understat': 6665, 'position': 'MID', 'starter': False},
               {'fpl': 575, 'name': 'Neco Williams', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 202, 'name': 'Aymeric Laporte', 'understat': 2498, 'position': 'DEF', 'starter': False},
               {'fpl': 203, 'name': 'Kyle Walker', 'understat': 638, 'position': 'DEF', 'starter': True},
               {'fpl': 204, 'name': 'Benjamin Mendy', 'understat': 3389, 'position': 'DEF', 'starter': True},
               {'fpl': 206, 'name': 'Oleksandr Zinchenko', 'understat': 2958, 'position': 'DEF', 'starter': True},
               {'fpl': 207, 'name': 'John Stones', 'understat': 586, 'position': 'DEF', 'starter': True},
               {'fpl': 208, 'name': 'Nicolás Otamendi', 'understat': 611, 'position': 'DEF', 'starter': True},
               {'fpl': 209, 'name': 'Danilo Luiz da Silva', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 210, 'name': 'Sergio Agüero', 'understat': 619, 'position': 'FOR', 'starter': True},
               {'fpl': 211, 'name': 'Gabriel Jesus', 'understat': 5543, 'position': 'FOR', 'starter': True},
               {'fpl': 212, 'name': 'Ederson', 'understat': 6054, 'position': 'GKP', 'starter': True},
               {'fpl': 213, 'name': 'Claudio Bravo', 'understat': 1731, 'position': 'GKP', 'starter': False},
               {'fpl': 214, 'name': 'Raheem Sterling', 'understat': 618, 'position': 'MID', 'starter': True},
               {'fpl': 215, 'name': 'Kevin De Bruyne', 'understat': 447, 'position': 'MID', 'starter': True},
               {'fpl': 216, 'name': 'Leroy Sané', 'understat': 337, 'position': 'MID', 'starter': False},
               {'fpl': 217, 'name': 'Riyad Mahrez', 'understat': 750, 'position': 'MID', 'starter': True},
               {'fpl': 218, 'name': 'Bernardo Silva', 'understat': 3635, 'position': 'MID', 'starter': True},
               {'fpl': 219, 'name': 'David Silva', 'understat': 617, 'position': 'MID', 'starter': False},
               {'fpl': 220, 'name': 'Phil Foden', 'understat': 6055, 'position': 'MID', 'starter': True},
               {'fpl': 221, 'name': 'Fernando Luiz Rosa', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 222, 'name': 'Ilkay Gündogan', 'understat': 314, 'position': 'MID', 'starter': True},
               {'fpl': 440, 'name': 'Angeliño', 'understat': 1040, 'position': 'DEF', 'starter': False},
               {'fpl': 443, 'name': 'Rodrigo Hernandez', 'understat': 2496, 'position': 'MID', 'starter': True},
               {'fpl': 518, 'name': 'João Pedro Cavaco Cancelo', 'understat': 2379, 'position': 'DEF', 'starter': False},
               {'fpl': 544, 'name': 'Eric Garcia', 'understat': 8045, 'position': 'DEF', 'starter': False},
               {'fpl': 562, 'name': 'Scott Carson', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 122, 'name': 'Aaron Wan-Bissaka', 'understat': 5584, 'position': 'DEF', 'starter': True},
               {'fpl': 160, 'name': 'Harry Maguire', 'understat': 1687, 'position': 'DEF', 'starter': True},
               {'fpl': 223, 'name': 'Chris Smalling', 'understat': 628, 'position': 'DEF', 'starter': False},
               {'fpl': 224, 'name': 'Ashley Young', 'understat': 631, 'position': 'DEF', 'starter': False},
               {'fpl': 225, 'name': 'Victor Lindelöf', 'understat': 6080, 'position': 'DEF', 'starter': True},
               {'fpl': 226, 'name': 'Luke Shaw', 'understat': 1006, 'position': 'DEF', 'starter': True},
               {'fpl': 227, 'name': 'Marcos Rojo', 'understat': 550, 'position': 'DEF', 'starter': False},
               {'fpl': 228, 'name': 'Eric Bailly', 'understat': 1739, 'position': 'DEF', 'starter': False},
               {'fpl': 229, 'name': 'José Diogo Dalot Teixeira', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 230, 'name': 'Matteo Darmian', 'understat': 557, 'position': 'DEF', 'starter': False},
               {'fpl': 231, 'name': 'Phil Jones', 'understat': 951, 'position': 'DEF', 'starter': False},
               {'fpl': 232, 'name': 'Romelu Lukaku', 'understat': 594, 'position': 'FOR', 'starter': False},
               {'fpl': 233, 'name': 'Marcus Rashford', 'understat': 556, 'position': 'FOR', 'starter': True},
               {'fpl': 234, 'name': 'Mason Greenwood', 'understat': 7490, 'position': 'FOR', 'starter': True},
               {'fpl': 235, 'name': 'David de Gea', 'understat': 546, 'position': 'GKP', 'starter': True},
               {'fpl': 236, 'name': 'Sergio Romero', 'understat': 560, 'position': 'GKP', 'starter': False},
               {'fpl': 237, 'name': 'Lee Grant', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 238, 'name': 'Paul Pogba', 'understat': 1740, 'position': 'MID', 'starter': True},
               {'fpl': 239, 'name': 'Anthony Martial', 'understat': 553, 'position': 'MID', 'starter': True},
               {'fpl': 240, 'name': 'Alexis Sánchez', 'understat': 498, 'position': 'MID', 'starter': False},
               {'fpl': 241, 'name': 'Jesse Lingard', 'understat': 558, 'position': 'MID', 'starter': True},
               {'fpl': 242, 'name': 'Juan Mata', 'understat': 554, 'position': 'MID', 'starter': False},
               {'fpl': 243, 'name': 'Daniel James', 'understat': 5595, 'position': 'MID', 'starter': True},
               {'fpl': 244, 'name': 'Frederico Rodrigues de Paula Santos', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 245, 'name': 'Angel Gomes', 'understat': 5598, 'position': 'MID', 'starter': False},
               {'fpl': 246, 'name': 'Andreas Pereira', 'understat': 922, 'position': 'MID', 'starter': True},
               {'fpl': 247, 'name': 'Nemanja Matic', 'understat': 697, 'position': 'MID', 'starter': False},
               {'fpl': 248, 'name': 'Scott McTominay', 'understat': 5560, 'position': 'MID', 'starter': True},
               {'fpl': 249, 'name': 'Tahith Chong', 'understat': 7439, 'position': 'MID', 'starter': False},
               {'fpl': 250, 'name': 'James Garner', 'understat': 7438, 'position': 'MID', 'starter': False},
               {'fpl': 481, 'name': 'Axel Tuanzebe', 'understat': 934, 'position': 'DEF', 'starter': False},
               {'fpl': 549, 'name': 'Brandon Williams', 'understat': 8075, 'position': 'DEF', 'starter': True},
               {'fpl': 251, 'name': 'Matt Ritchie', 'understat': 461, 'position': 'DEF', 'starter': False},
               {'fpl': 252, 'name': 'Fabian Schär', 'understat': 76, 'position': 'DEF', 'starter': True},
               {'fpl': 253, 'name': 'DeAndre Yedlin', 'understat': 727, 'position': 'DEF', 'starter': False},
               {'fpl': 254, 'name': 'Federico Fernández', 'understat': 708, 'position': 'DEF', 'starter': True},
               {'fpl': 255, 'name': 'Paul Dummett', 'understat': 853, 'position': 'DEF', 'starter': False},
               {'fpl': 256, 'name': 'Javier Manquillo', 'understat': 1719, 'position': 'DEF', 'starter': True},
               {'fpl': 257, 'name': 'Florian Lejeune', 'understat': 5073, 'position': 'DEF', 'starter': False},
               {'fpl': 258, 'name': 'Jamaal Lascelles', 'understat': 766, 'position': 'DEF', 'starter': False},
               {'fpl': 259, 'name': 'Ciaran Clark', 'understat': 875, 'position': 'DEF', 'starter': False},
               {'fpl': 260, 'name': 'Yoshinori Muto', 'understat': 47, 'position': 'FOR', 'starter': False},
               {'fpl': 261, 'name': 'Jose Luis Mato Sanmartín', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 262, 'name': 'Martin Dubravka', 'understat': 6532, 'position': 'GKP', 'starter': True},
               {'fpl': 263, 'name': 'Karl Darlow', 'understat': 780, 'position': 'GKP', 'starter': False},
               {'fpl': 264, 'name': 'Frederick Woodman', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 266, 'name': 'Miguel Almirón', 'understat': 7420, 'position': 'MID', 'starter': True},
               {'fpl': 267, 'name': 'Christian Atsu', 'understat': 2344, 'position': 'MID', 'starter': True},
               {'fpl': 268, 'name': 'Sung-yueng Ki', 'understat': 723, 'position': 'MID', 'starter': False},
               {'fpl': 269, 'name': 'Jonjo Shelvey', 'understat': 769, 'position': 'MID', 'starter': True},
               {'fpl': 270, 'name': 'Sean Longstaff', 'understat': 7078, 'position': 'MID', 'starter': True},
               {'fpl': 271, 'name': 'Isaac Hayden', 'understat': 6062, 'position': 'MID', 'starter': True},
               {'fpl': 466, 'name': 'Joelinton', 'understat': 87, 'position': 'FOR', 'starter': True},
               {'fpl': 482, 'name': 'Jack Colback', 'understat': 767, 'position': 'MID', 'starter': False},
               {'fpl': 483, 'name': 'Jacob Murphy', 'understat': 6063, 'position': 'MID', 'starter': False},
               {'fpl': 498, 'name': 'Jetro Willems', 'understat': 6143, 'position': 'DEF', 'starter': True},
               {'fpl': 499, 'name': 'Rolando Aarons', 'understat': 915, 'position': 'MID', 'starter': False},
               {'fpl': 500, 'name': 'Allan Saint-Maximin', 'understat': 101, 'position': 'MID', 'starter': False},
               {'fpl': 519, 'name': 'Emil Krafth', 'understat': 1545, 'position': 'DEF', 'starter': False},
               {'fpl': 520, 'name': 'Andy Carroll', 'understat': 537, 'position': 'FOR', 'starter': True},
               {'fpl': 540, 'name': 'Matthew Longstaff', 'understat': 8016, 'position': 'MID', 'starter': False},
               {'fpl': 554, 'name': 'Dwight Gayle', 'understat': 743, 'position': 'FOR', 'starter': False},
               {'fpl': 573, 'name': 'Robert Elliot', 'understat': 763, 'position': 'GKP', 'starter': False},
               {'fpl': 272, 'name': 'Timm Klose', 'understat': 162, 'position': 'DEF', 'starter': False},
               {'fpl': 273, 'name': 'Ben Godfrey', 'understat': 7689, 'position': 'DEF', 'starter': False},
               {'fpl': 274, 'name': 'Maximillian Aarons', 'understat': 7688, 'position': 'DEF', 'starter': True},
               {'fpl': 275, 'name': 'Christoph Zimmermann', 'understat': 7990, 'position': 'DEF', 'starter': True},
               {'fpl': 276, 'name': 'Jamal Lewis', 'understat': 7691, 'position': 'DEF', 'starter': False},
               {'fpl': 277, 'name': 'Grant Hanley', 'understat': 7690, 'position': 'DEF', 'starter': True},
               {'fpl': 278, 'name': 'Teemu Pukki', 'understat': 7696, 'position': 'FOR', 'starter': True},
               {'fpl': 279, 'name': 'Dennis Srbeny', 'understat': 7822, 'position': 'FOR', 'starter': False},
               {'fpl': 280, 'name': 'Tim Krul', 'understat': 982, 'position': 'GKP', 'starter': True},
               {'fpl': 281, 'name': 'Michael McGovern', 'understat': 8022, 'position': 'GKP', 'starter': False},
               {'fpl': 282, 'name': 'Mario Vrancic', 'understat': 12, 'position': 'MID', 'starter': False},
               {'fpl': 283, 'name': 'Emiliano Buendía', 'understat': 2203, 'position': 'MID', 'starter': True},
               {'fpl': 284, 'name': 'Onel Hernández', 'understat': 7697, 'position': 'MID', 'starter': True},
               {'fpl': 285, 'name': 'Marco Stiepermann', 'understat': 7694, 'position': 'MID', 'starter': False},
               {'fpl': 286, 'name': 'Kenny McLean', 'understat': 7693, 'position': 'MID', 'starter': True},
               {'fpl': 287, 'name': 'Todd Cantwell', 'understat': 7695, 'position': 'MID', 'starter': True},
               {'fpl': 288, 'name': 'Moritz Leitner', 'understat': 1217, 'position': 'MID', 'starter': False},
               {'fpl': 289, 'name': 'Alexander Tettey', 'understat': 791, 'position': 'MID', 'starter': True},
               {'fpl': 290, 'name': 'Tom Trybull', 'understat': 7692, 'position': 'MID', 'starter': True},
               {'fpl': 434, 'name': 'Josip Drmic', 'understat': 209, 'position': 'FOR', 'starter': False},
               {'fpl': 435, 'name': 'Patrick Roberts', 'understat': 925, 'position': 'MID', 'starter': False},
               {'fpl': 449, 'name': 'Ralf Fahrmann', 'understat': 330, 'position': 'GKP', 'starter': False},
               {'fpl': 454, 'name': 'Sam Byram', 'understat': 902, 'position': 'DEF', 'starter': True},
               {'fpl': 484, 'name': 'Philip Heise', 'understat': 70, 'position': 'DEF', 'starter': False},
               {'fpl': 507, 'name': 'Ibrahim Amadou', 'understat': 3358, 'position': 'MID', 'starter': False},
               {'fpl': 538, 'name': 'Adam Idah', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 551, 'name': 'Archie Mair', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 552, 'name': 'Akin Famewo', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 70, 'name': 'Lys Mousset', 'understat': 1748, 'position': 'FOR', 'starter': True},
               {'fpl': 291, 'name': 'Enda Stevens', 'understat': 7707, 'position': 'DEF', 'starter': True},
               {'fpl': 292, 'name': 'Kieron Freeman', 'understat': 7713, 'position': 'DEF', 'starter': False},
               {'fpl': 293, 'name': "Jack O'Connell", 'understat': 7705, 'position': 'DEF', 'starter': True},
               {'fpl': 294, 'name': 'George Baldock', 'understat': 7706, 'position': 'DEF', 'starter': True},
               {'fpl': 295, 'name': 'John Egan', 'understat': 7703, 'position': 'DEF', 'starter': True},
               {'fpl': 296, 'name': 'Richard Stearman', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 297, 'name': 'John Lundstram', 'understat': 7708, 'position': 'DEF', 'starter': True},
               {'fpl': 298, 'name': 'Billy Sharp', 'understat': 7712, 'position': 'FOR', 'starter': False},
               {'fpl': 299, 'name': 'Jake Eastwood', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 300, 'name': 'Mark Duffy', 'understat': None, 'position': 'DEF', 'starter': False},
               {'fpl': 301, 'name': 'John Fleck', 'understat': 7709, 'position': 'MID', 'starter': True},
               {'fpl': 302, 'name': 'Oliver Norwood', 'understat': 7710, 'position': 'MID', 'starter': True},
               {'fpl': 303, 'name': 'David McGoldrick', 'understat': 7711, 'position': 'FOR', 'starter': True},
               {'fpl': 423, 'name': 'Chris Basham', 'understat': 7704, 'position': 'DEF', 'starter': True},
               {'fpl': 436, 'name': 'Simon Moore', 'understat': 7715, 'position': 'GKP', 'starter': False},
               {'fpl': 441, 'name': 'Luke Freeman', 'understat': 7713, 'position': 'MID', 'starter': False},
               {'fpl': 444, 'name': 'Phil Jagielka', 'understat': 587, 'position': 'DEF', 'starter': False},
               {'fpl': 453, 'name': 'Callum Robinson', 'understat': 4476, 'position': 'MID', 'starter': False},
               {'fpl': 456, 'name': 'Ravel Morrison', 'understat': 1883, 'position': 'MID', 'starter': False},
               {'fpl': 471, 'name': 'Dean Henderson', 'understat': 7702, 'position': 'GKP', 'starter': True},
               {'fpl': 472, 'name': 'Ben Osborn', 'understat': 7714, 'position': 'MID', 'starter': False},
               {'fpl': 501, 'name': 'Oliver McBurnie', 'understat': 1736, 'position': 'FOR', 'starter': True},
               {'fpl': 521, 'name': 'Michael Verrips', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 522, 'name': 'Muhamed Bešić', 'understat': 908, 'position': 'MID', 'starter': False},
               {'fpl': 547, 'name': 'Leon Clarke', 'understat': 8061, 'position': 'DEF', 'starter': False},
               {'fpl': 304, 'name': 'Jannik Vestergaard', 'understat': 111, 'position': 'DEF', 'starter': False},
               {'fpl': 305, 'name': 'Ryan Bertrand', 'understat': 835, 'position': 'DEF', 'starter': True},
               {'fpl': 306, 'name': 'Yan Valery', 'understat': 7280, 'position': 'DEF', 'starter': False},
               {'fpl': 307, 'name': 'Jan Bednarek', 'understat': 6042, 'position': 'DEF', 'starter': True},
               {'fpl': 308, 'name': 'Jack Stephens', 'understat': 1735, 'position': 'DEF', 'starter': True},
               {'fpl': 310, 'name': 'Maya Yoshida', 'understat': 845, 'position': 'DEF', 'starter': False},
               {'fpl': 311, 'name': 'Kayne Ramsay', 'understat': 7326, 'position': 'DEF', 'starter': False},
               {'fpl': 312, 'name': 'Charlie Austin', 'understat': 848, 'position': 'FOR', 'starter': False},
               {'fpl': 313, 'name': 'Danny Ings', 'understat': 986, 'position': 'FOR', 'starter': True},
               {'fpl': 314, 'name': 'Michael Obafemi', 'understat': 6504, 'position': 'FOR', 'starter': True},
               {'fpl': 315, 'name': 'Shane Long', 'understat': 839, 'position': 'FOR', 'starter': True},
               {'fpl': 316, 'name': 'Sam Gallagher', 'understat': 4483, 'position': 'FOR', 'starter': False},
               {'fpl': 317, 'name': 'Fraser Forster', 'understat': 831, 'position': 'GKP', 'starter': False},
               {'fpl': 318, 'name': 'Alex McCarthy', 'understat': 635, 'position': 'GKP', 'starter': True},
               {'fpl': 319, 'name': 'Angus Gunn', 'understat': 5544, 'position': 'GKP', 'starter': True},
               {'fpl': 320, 'name': 'Nathan Redmond', 'understat': 790, 'position': 'MID', 'starter': False},
               {'fpl': 321, 'name': 'James Ward-Prowse', 'understat': 843, 'position': 'MID', 'starter': True},
               {'fpl': 322, 'name': 'Mohamed Elyounoussi', 'understat': 6894, 'position': 'MID', 'starter': False},
               {'fpl': 323, 'name': 'Stuart Armstrong', 'understat': 6893, 'position': 'MID', 'starter': True},
               {'fpl': 324, 'name': 'Mario Lemina', 'understat': 1299, 'position': 'MID', 'starter': False},
               {'fpl': 325, 'name': 'Pierre-Emile Højbjerg', 'understat': 343, 'position': 'MID', 'starter': False},
               {'fpl': 326, 'name': 'Tyreke Johnson', 'understat': 7314, 'position': 'MID', 'starter': False},
               {'fpl': 327, 'name': 'Callum Slattery', 'understat': 7335, 'position': 'MID', 'starter': False},
               {'fpl': 328, 'name': 'Oriol Romeu Vidal', 'understat': 842, 'position': 'MID', 'starter': False},
               {'fpl': 437, 'name': 'Che Adams', 'understat': 7700, 'position': 'FOR', 'starter': True},
               {'fpl': 438, 'name': 'Moussa Djenepo', 'understat': 7701, 'position': 'MID', 'starter': False},
               {'fpl': 485, 'name': 'Wesley Hoedt', 'understat': 1203, 'position': 'DEF', 'starter': False},
               {'fpl': 486, 'name': 'Cédric Soares', 'understat': 847, 'position': 'DEF', 'starter': True},
               {'fpl': 508, 'name': 'Sofiane Boufal', 'understat': 1734, 'position': 'MID', 'starter': False},
               {'fpl': 532, 'name': 'Kevin Danso', 'understat': 5261, 'position': 'DEF', 'starter': False},
               {'fpl': 535, 'name': "Daniel N'Lundulu", 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 548, 'name': 'Harry Lewis', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 329, 'name': 'Ben Davies', 'understat': 660, 'position': 'DEF', 'starter': False},
               {'fpl': 330, 'name': 'Jan Vertonghen', 'understat': 640, 'position': 'DEF', 'starter': True},
               {'fpl': 331, 'name': 'Toby Alderweireld', 'understat': 639, 'position': 'DEF', 'starter': True},
               {'fpl': 332, 'name': 'Danny Rose', 'understat': 641, 'position': 'DEF', 'starter': False},
               {'fpl': 333, 'name': 'Davinson Sánchez', 'understat': 6249, 'position': 'DEF', 'starter': True},
               {'fpl': 334, 'name': 'Kieran Trippier', 'understat': 652, 'position': 'DEF', 'starter': False},
               {'fpl': 335, 'name': 'Juan Foyth', 'understat': 6306, 'position': 'DEF', 'starter': False},
               {'fpl': 336, 'name': 'Serge Aurier', 'understat': 3600, 'position': 'DEF', 'starter': True},
               {'fpl': 338, 'name': 'Harry Kane', 'understat': 647, 'position': 'FOR', 'starter': True},
               {'fpl': 339, 'name': 'Vincent Janssen', 'understat': 1730, 'position': 'FOR', 'starter': False},
               {'fpl': 340, 'name': 'Hugo Lloris', 'understat': 637, 'position': 'GKP', 'starter': False},
               {'fpl': 341, 'name': 'Paulo Gazzaniga', 'understat': 973, 'position': 'GKP', 'starter': True},
               {'fpl': 342, 'name': 'Heung-Min Son', 'understat': 453, 'position': 'MID', 'starter': False},
               {'fpl': 343, 'name': 'Christian Eriksen', 'understat': 646, 'position': 'MID', 'starter': True},
               {'fpl': 344, 'name': 'Bamidele Alli', 'understat': 645, 'position': 'MID', 'starter': True},
               {'fpl': 345, 'name': 'Lucas Moura', 'understat': 3293, 'position': 'MID', 'starter': True},
               {'fpl': 346, 'name': 'Erik Lamela', 'understat': 644, 'position': 'MID', 'starter': False},
               {'fpl': 347, 'name': 'Harry Winks', 'understat': 971, 'position': 'MID', 'starter': True},
               {'fpl': 348, 'name': 'Victor Wanyama', 'understat': 836, 'position': 'MID', 'starter': False},
               {'fpl': 349, 'name': 'Moussa Sissoko', 'understat': 772, 'position': 'MID', 'starter': True},
               {'fpl': 350, 'name': 'Eric Dier', 'understat': 643, 'position': 'MID', 'starter': True},
               {'fpl': 351, 'name': 'Luke Amos', 'understat': 6819, 'position': 'MID', 'starter': False},
               {'fpl': 352, 'name': 'Oliver Skipp', 'understat': 7198, 'position': 'MID', 'starter': False},
               {'fpl': 442, 'name': 'Tanguy Ndombele', 'understat': 5962, 'position': 'MID', 'starter': True},
               {'fpl': 509, 'name': 'Troy Parrott', 'understat': 8145, 'position': 'FOR', 'starter': False},
               {'fpl': 523, 'name': 'Giovani Lo Celso', 'understat': 5681, 'position': 'MID', 'starter': False},
               {'fpl': 524, 'name': 'Ryan Sessegnon', 'understat': 6837, 'position': 'MID', 'starter': False},
               {'fpl': 527, 'name': 'Georges-Kévin Nkoudou', 'understat': 1729, 'position': 'MID', 'starter': False},
               {'fpl': 543, 'name': 'Alfie Whiteman', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 555, 'name': 'Michel Vorm', 'understat': 651, 'position': 'GKP', 'starter': False},
               {'fpl': 558, 'name': 'Brandon Austin', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 353, 'name': 'José Holebas', 'understat': 568, 'position': 'DEF', 'starter': False},
               {'fpl': 354, 'name': 'Christian Kabasele', 'understat': 1725, 'position': 'DEF', 'starter': False},
               {'fpl': 355, 'name': 'Adam Masina', 'understat': 1441, 'position': 'DEF', 'starter': False},
               {'fpl': 356, 'name': 'Adrian Mariappa', 'understat': 524, 'position': 'DEF', 'starter': False},
               {'fpl': 357, 'name': 'Francisco Femenía Far', 'understat': 5043, 'position': 'DEF', 'starter': False},
               {'fpl': 358, 'name': 'Craig Cathcart', 'understat': 581, 'position': 'DEF', 'starter': True},
               {'fpl': 359, 'name': 'Daryl Janmaat', 'understat': 764, 'position': 'DEF', 'starter': False},
               {'fpl': 360, 'name': 'Marc Navarro', 'understat': 5085, 'position': 'DEF', 'starter': False},
               {'fpl': 361, 'name': 'Sebastian Prödl', 'understat': 566, 'position': 'DEF', 'starter': False},
               {'fpl': 362, 'name': 'Troy Deeney', 'understat': 574, 'position': 'FOR', 'starter': True},
               {'fpl': 363, 'name': 'Gerard Deulofeu', 'understat': 591, 'position': 'FOR', 'starter': True},
               {'fpl': 364, 'name': 'Andre Gray', 'understat': 1660, 'position': 'FOR', 'starter': False},
               {'fpl': 365, 'name': 'Isaac Success Ajayi', 'understat': 1724, 'position': 'FOR', 'starter': False},
               {'fpl': 366, 'name': 'Ben Foster', 'understat': 803, 'position': 'GKP', 'starter': True},
               {'fpl': 367, 'name': 'Pontus Dahlberg', 'understat': None, 'position': 'GKP', 'starter': False},
               {'fpl': 368, 'name': 'Abdoulaye Doucouré', 'understat': 1726, 'position': 'MID', 'starter': False},
               {'fpl': 369, 'name': 'Roberto Pereyra', 'understat': 1723, 'position': 'MID', 'starter': False},
               {'fpl': 370, 'name': 'Will Hughes', 'understat': 6104, 'position': 'MID', 'starter': True},
               {'fpl': 371, 'name': 'Tom Cleverley', 'understat': 596, 'position': 'MID', 'starter': False},
               {'fpl': 372, 'name': 'Ken Sema', 'understat': 6841, 'position': 'MID', 'starter': False},
               {'fpl': 373, 'name': 'Etienne Capoue', 'understat': 572, 'position': 'MID', 'starter': True},
               {'fpl': 374, 'name': 'Nathaniel Chalobah', 'understat': 1677, 'position': 'MID', 'starter': False},
               {'fpl': 375, 'name': 'Domingos Quina', 'understat': 5573, 'position': 'MID', 'starter': False},
               {'fpl': 439, 'name': 'Craig Dawson', 'understat': 804, 'position': 'DEF', 'starter': False},
               {'fpl': 512, 'name': 'Danny Welbeck', 'understat': 501, 'position': 'FOR', 'starter': False},
               {'fpl': 513, 'name': 'Heurelho da Silva Gomes', 'understat': 564, 'position': 'GKP', 'starter': False},
               {'fpl': 525, 'name': 'Ismaïla Sarr', 'understat': 5675, 'position': 'MID', 'starter': True},
               {'fpl': 542, 'name': 'Dimitri Foulquier', 'understat': 2509, 'position': 'DEF', 'starter': False},
               {'fpl': 563, 'name': 'Ayotomiwa Dele-Bashiru', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 376, 'name': 'Aaron Cresswell', 'understat': 534, 'position': 'DEF', 'starter': True},
               {'fpl': 377, 'name': 'Angelo Ogbonna', 'understat': 528, 'position': 'DEF', 'starter': True},
               {'fpl': 378, 'name': 'Arthur Masuaku', 'understat': 1760, 'position': 'DEF', 'starter': True},
               {'fpl': 379, 'name': 'Pablo Zabaleta', 'understat': 610, 'position': 'DEF', 'starter': False},
               {'fpl': 380, 'name': 'Ryan Fredericks', 'understat': 6891, 'position': 'DEF', 'starter': False},
               {'fpl': 381, 'name': 'Issa Diop', 'understat': 3203, 'position': 'DEF', 'starter': True},
               {'fpl': 382, 'name': 'Fabián Balbuena', 'understat': 6892, 'position': 'DEF', 'starter': True},
               {'fpl': 383, 'name': 'Winston Reid', 'understat': 529, 'position': 'DEF', 'starter': False},
               {'fpl': 384, 'name': 'Ben Johnson', 'understat': 6424, 'position': 'DEF', 'starter': False},
               {'fpl': 385, 'name': 'Marko Arnautovic', 'understat': 865, 'position': 'FOR', 'starter': False},
               {'fpl': 386, 'name': 'Javier Hernández Balcázar', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 387, 'name': 'Alexandre Nascimento Costa Silva', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 388, 'name': 'Lukasz Fabianski', 'understat': 706, 'position': 'GKP', 'starter': False},
               {'fpl': 389, 'name': 'Michail Antonio', 'understat': 531, 'position': 'MID', 'starter': True},
               {'fpl': 390, 'name': 'Felipe Anderson', 'understat': 1208, 'position': 'MID', 'starter': True},
               {'fpl': 391, 'name': 'Manuel Lanzini', 'understat': 535, 'position': 'MID', 'starter': False},
               {'fpl': 392, 'name': 'Andriy Yarmolenko', 'understat': 6274, 'position': 'MID', 'starter': False},
               {'fpl': 393, 'name': 'Robert Snodgrass', 'understat': 1691, 'position': 'MID', 'starter': True},
               {'fpl': 394, 'name': 'Jack Wilshere', 'understat': 1036, 'position': 'MID', 'starter': False},
               {'fpl': 395, 'name': 'Declan Rice', 'understat': 5553, 'position': 'MID', 'starter': True},
               {'fpl': 396, 'name': 'Mark Noble', 'understat': 533, 'position': 'MID', 'starter': True},
               {'fpl': 397, 'name': 'Carlos Sánchez', 'understat': 667, 'position': 'MID', 'starter': False},
               {'fpl': 398, 'name': 'Grady Diangana', 'understat': 6651, 'position': 'MID', 'starter': False},
               {'fpl': 399, 'name': 'Pablo Fornals', 'understat': 2335, 'position': 'MID', 'starter': True},
               {'fpl': 400, 'name': 'Pedro Obiang', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 450, 'name': 'Roberto Jimenez Gago', 'understat': 5087, 'position': 'GKP', 'starter': False},
               {'fpl': 457, 'name': 'Sébastien Haller', 'understat': 6144, 'position': 'FOR', 'starter': True},
               {'fpl': 514, 'name': 'Albian Ajeti', 'understat': 2673, 'position': 'FOR', 'starter': False},
               {'fpl': 553, 'name': 'David Martin', 'understat': 8082, 'position': 'GKP', 'starter': True},
               {'fpl': 568, 'name': 'Nathan Holland', 'understat': 5567, 'position': 'MID', 'starter': False},
               {'fpl': 401, 'name': 'Matt Doherty', 'understat': 6852, 'position': 'DEF', 'starter': True},
               {'fpl': 402, 'name': 'Jonny', 'understat': 2280, 'position': 'DEF', 'starter': True},
               {'fpl': 403, 'name': 'Conor Coady', 'understat': 6851, 'position': 'DEF', 'starter': True},
               {'fpl': 404, 'name': 'Ryan Bennett', 'understat': 787, 'position': 'DEF', 'starter': False},
               {'fpl': 405, 'name': 'Willy Boly', 'understat': 6850, 'position': 'DEF', 'starter': False},
               {'fpl': 406, 'name': 'Rúben Gonçalo Silva Nascimento Vinagre', 'understat': 6856, 'position': 'DEF', 'starter': False},
               {'fpl': 407, 'name': 'Romain Saïss', 'understat': 3491, 'position': 'DEF', 'starter': True},
               {'fpl': 408, 'name': 'Max Kilman', 'understat': 7332, 'position': 'DEF', 'starter': False},
               {'fpl': 409, 'name': 'Raúl Jiménez', 'understat': 4105, 'position': 'FOR', 'starter': True},
               {'fpl': 410, 'name': 'Diogo Jota', 'understat': 6854, 'position': 'FOR', 'starter': True},
               {'fpl': 411, 'name': 'Rui Patrício', 'understat': 6849, 'position': 'GKP', 'starter': True},
               {'fpl': 412, 'name': 'John Ruddy', 'understat': 785, 'position': 'GKP', 'starter': False},
               {'fpl': 413, 'name': 'Will Norris', 'understat': 7459, 'position': 'GKP', 'starter': False},
               {'fpl': 414, 'name': 'Rúben Neves', 'understat': 6853, 'position': 'MID', 'starter': True},
               {'fpl': 415, 'name': 'João Filipe Moutinho', 'understat': 3422, 'position': 'MID', 'starter': True},
               {'fpl': 416, 'name': 'Morgan Gibbs-White', 'understat': 6857, 'position': 'MID', 'starter': False},
               {'fpl': 417, 'name': 'Adama Traoré', 'understat': 900, 'position': 'MID', 'starter': True},
               {'fpl': 418, 'name': 'Hélder Costa', 'understat': 3428, 'position': 'MID', 'starter': False},
               {'fpl': 419, 'name': 'Ivan Cavaleiro', 'understat': 3683, 'position': 'MID', 'starter': False},
               {'fpl': 420, 'name': 'Leander Dendoncker', 'understat': 7236, 'position': 'MID', 'starter': True},
               {'fpl': 473, 'name': 'Jesús Vallejo Lázaro', 'understat': 5234, 'position': 'DEF', 'starter': False},
               {'fpl': 487, 'name': 'Patrick Cutrone', 'understat': 4918, 'position': 'FOR', 'starter': False},
               {'fpl': 528, 'name': 'Pedro Lomba Neto', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 559, 'name': 'Bernard Ashley-Seal', 'understat': None, 'position': 'FOR', 'starter': False},
               {'fpl': 560, 'name': 'Taylor Perry', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 566, 'name': 'Owen Otasowie', 'understat': None, 'position': 'MID', 'starter': False},
               {'fpl': 567, 'name': 'Luke Cundle', 'understat': None, 'position': 'MID', 'starter': False}]


def getPlayer(title, inp, outp):
    accenteds = ['é', 'ê', 'ë', 'ü', 'ú', 'î', 'ï', 'í', 'ì', 'ô', 'ö', 'ò', 'ó', 'ø', 'õ', 'œ', 'à', 'á', 'â', 'ä', 'ã', 'æ', 'ß', 'ś', 'š', 'ł', 'ž', 'ź', 'ç', 'ć', 'č', 'ñ', 'ń']
    correspondings = ['e', 'e', 'e', 'u', 'u', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'o', 'oe', 'a', 'a', 'a', 'a', 'a', 'ae', 'ss', 's', 's', 'l', 'z', 'z', 'c', 'c', 'c', 'n', 'n']
    if inp == 'fpl' or inp == 'understat':
        return [i[outp] for i in playerNames if i[inp] == title][0]
    elif inp == 'name':
        inp = inp.split()
        possibleNames = []
        title = str.lower(title)
        for tIndex, char in enumerate(title):
            for index, letter in enumerate(accenteds):
                if char == letter:
                    title = title[:tIndex] + correspondings[index] + title[tIndex + 1:]
        for player in playerNames:
            name = str.lower(player['name'])
            for tIndex, char in enumerate(name):
                for index, letter in enumerate(accenteds):
                    if char == letter:
                        name = name[:tIndex] + correspondings[index] + name[tIndex + 1:]
            if title in name:
                possibleNames.append(player)
        if len(possibleNames) == 1:
            return possibleNames[0][outp]
        else:
            print(title)
            raise ValueError('Player Indefinite')
